apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: express-app-k8s
  name: express-app-k8s
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: express-app-k8s
status:
  loadBalancer: {}