name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run shell script
      run: echo commit hash is ${{ github.sha }}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
  
    - name: Build Docker Image and Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/express-app-kubernetes:${{ github.sha }}

    - name: Update config files in azure K8s
      run: sed -i.bak 's/{{tag}}/${{ github.sha }}/g' azureK8s/deploy.yaml  && rm azureK8s/*.bak

    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f ./azurek8s